### ISSUE TITLE
Extension specific: Handling CORS related issues

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#11]
(This problem is not applicable to SDK)

How do we go about handling these issues? Create sub-issues if required.

1. Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

2. Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'report-sample' 'sha256-6gLjSWp3GRKZCUFvRX5aGHtECD1wVRgJOJp7r0ZQjV0=' 'unsafe-inline' static.licdn.com s.c.lnkd.licdn.com static-fstl.licdn.com static-src.linkedin.com https://www.linkedin.com/voyager/service-worker-push.js static-exp1.licdn.com static-exp2.licdn.com static-exp3.licdn.com s.c.exp1.licdn.com s.c.exp2.licdn.com static-lcdn.licdn.com s.c.lcdn.licdn.com https://www.linkedin.com/sc/ https://www.linkedin.com/scds/ https://qprod.www.linkedin.com/sc/ https://www.linkedin.com/sw.js https://www.linkedin.com/voyager/abp-detection.js https://snap.licdn.com/li.lms-analytics/insight.min.js https://platform.linkedin.com/js/analytics.js https://platform-akam.linkedin.com/js/analytics.js https://platform-ecst.linkedin.com/js/analytics.js https://platform-azur.linkedin.com/js/analytics.js https://platform.linkedin.com/litms/utag/ https://platform-akam.linkedin.com/litms/utag/ https://platform-ecst.linkedin.com/litms/utag/ https://platform-azur.linkedin.com/litms/utag/ https://platform.linkedin.com/litms/vendor/ https://platform-akam.linkedin.com/litms/vendor/ https://platform-ecst.linkedin.com/litms/vendor/ https://platform-azur.linkedin.com/litms/vendor/". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

Context
https://www.linkedin.com/feed/

3.

**Comment by yureshwar** [comment]
Duplicated by CSP issue
