### ISSUE TITLE
Node type detection

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#209]
Add dropdown selection for the clicked element and prepopulate the system detected clicked element and save the changes that the user has selected the element.

**Comment by kcramakrishna** [comment]
1. Label identified elements for ML
a. Are these limited list of things ? i.e. Do we know all possible elements? Can there be an 'other' in drop down ?
b. When developing ML solution, look at how to identify nested elements like "selection boxes in dropdown" etc.

**Comment by yureshwar** [comment]
We have identified the elements based on the list provided by the w3schools

https://www.w3schools.com/html/html_form_elements.asp
https://www.w3schools.com/html/html_form_input_types.asp

**Comment by yureshwar** [comment]
We have combined the list and grouped some of the element types. 

![image](https://user-images.githubusercontent.com/516516/171985149-1594d811-493e-4cae-890e-b0ed45049d1b.png)
