### ISSUE TITLE
'Deprecated' error noticed on browser: Synchronous XMLHttpReques

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#240]
Browser Error: 

Stack Trace
js/Voicepluginsdk.js:2447 (searchinelastic)
js/Voicepluginsdk.js:401 (recognition.onresult)

                translatexhr.open("POST", posturl, false);

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by yureshwar** [comment]
Fixed the issue
