### ISSUE TITLE
Performance improvement in showing search results

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#245]
We can further improve performance by splitting the data transfer process. We can initially transfer only the labels without the node data. Once a user clicks on the label, we can fetch the node data for that specific label. This should further reduce the data transfer to 100KB (estimated). Since this is significant effort, we can get to this when we really hit performance bottlenecks.

This is related to #197

**Comment by yureshwar** [comment]
Currently we have implemented gzip functionality on the server to serve the content
