### ISSUE TITLE
"Enterprise Feature": Enabling fine grained permissions in the Assistant

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#250]
SDK adoptees and Enterprises will have considerations like privacy and needing certain types of restrictions. We need to enable developers/integrators to incorporate fine grained controls on features as well as search results.

**Comment by kcramakrishna** [comment]
Problem:
UDAN enables creation of flows. Once a flow is created, it is available across the platform to all users irrespective of logical groupings like departments, locations, orgs etc. How do we enable fine grained access for flow creators to be able to control the ‘exposure of the flow’.  

Detailed Analysis:

1. The problem came into focus during discussions with vantagecircle.
2. Vantagecircle has multiple corporate clients and a concern was raised about restricting certain flows to certain organisations.
3. On exploration, it is realised that this is a specific case of a general problem - how do we restrict flows to specific groups of users for each nistapp customer. 
4. Nistapp customers may have very custom restrictions/behaviour based on very specific user groups. User groups can be:
4.a. Formal: security levels, roles, locations, departments, cross departmental groups   
4.b. Informal group: Interest groups, volunteer groups, 
6. The usual RBAC approach is limited:
6.a. Will quickly become unwieldy
6.b. Will become too complex and unusable if we try to encompass all possible scenarios.

Proposed Solution: JSON for customer configurable restriction:
1. Customer define json structure (will need basic structure validations)
2. These key values will appear during recording and the user can select whether a particular key needs to be matched during search.

Assumption:
Assumption is that elastic or similar tools will be able to index these permissions defined in json.

Proposed Implementation:
Have 3 json objects:
1. Nistapp mandatory json object: attributes like id, email etc which are mandatory. These can continue to exist as is implemented currently. Moving them into json may just help make it more structured and cleaner. This can be debated. 
1.a `{ // Variables passed by integrators to Nistapp 
“​​udaauthdata_id”: “<user Id passed by integrator>” //mandatory (we do validation for this)
“Uda..._emailid”: “emailId”
“Css_pathj”: “”
“Udaauthdata.restrict_add_delete”: “”}`

2. Application mandatory objects: Developers pass these objects to our plugin. These are usually key/values specific to Nistapp-clients(vantage) Eg: OrgId(as defined in vantage), userID, Location, etc. 
2.a Developers can define and pass as many key/value pairs as they want. Note(How do we handle multiple values? Do we give a multiselect dropdown?)
2.b For regular users, these will not even be displayed. All of them will be treated as ‘mandatory’ with default value as passed from object. These  key/value will be silently saved along with the activity. During search, all these key/value pairs will have to be mandatorily matched.
2.c Only “power users as defined by developers” will be shown an interface where they can mark some of these “non mandatory”. If marked “non-mandatory”, that specific key/value will NOT be saved along with the activity. 
2.d `{ // Target Application variables passed by developers
	{ 
{<var1>: “”
 Mandatory: “Yes/No”
}
{<var2>: “”
 Mandatory: “Yes/No”
}
{<var3>: “”
 Mandatory: “Yes/No”
}
…….
}
}`

3. End user json objects: End users(clients of our clients: Eg. Wipro which is a client of Vantage) may ask for some customisation based on internal departments, groups etc. Vantage can define key/values based on these requirements and pass them to UDAN app in this section. (Do we allow vantage to pass default “mandatory/non-mandatory” for each field? I think we should) These key/values will be displayed to the user when creating a flow. Users can mark these as “mandatory/non-mandatory” before saving.
3.a `{ // Target Application variables passed by developers but specific to Wipro
	{ 
{<var1>: “”
 Mandatory: “Yes/No”
}
{<var2>: “”
 Mandatory: “Yes/No”
}
{<var3>: “”
 Mandatory: “Yes/No”
}
…….
}
}`

**Comment by kcramakrishna** [comment]
https://dzone.com/articles/reactive-elasticsearch-with-quarkus
https://camel.apache.org/

**Comment by yureshwar** [comment]
For demonstrating the fine-grained permissions we need to put the following line in the console

udaauthdata.permissions = {companyId: 355, companyName: 'vantagecircle'};

**Comment by yureshwar** [comment]
Added the functionality as an enterprise feature.
