### ISSUE TITLE
User login functionality

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#254]
1. User login with google id: If the user is logged into Chrome (and sync is turned on), we can use those credentials to authenticate and authorise the user. We can prompt user to do this or chose an alternative to auth via google id (using Keycloak).

2. User login with FB

Both of above are related to below issue.

https://github.com/Digital-Assistant/digital-assistant-server/issues/8

**Comment by yureshwar** [comment]
Added login functionality via keycloak
