### ISSUE TITLE
Popup Message needs to be handled...Right now our app captures the steps to close such messahe---unnecessary overload on app

### ISSUE THREAD

**Issue by Gunasekkrann** [Digital-Assistant/Digital_Assistant_Client#268]
![Uploading Popup messages handling issue.PNG…]()

**Comment by kcramakrishna** [comment]
Image did not get uploaded properly. Please upload image again.

**Comment by Gunasekkrann** [comment]
Well this issue was opened to differentiate between dialogues and Ads popUps and captures the steps only for dialogues

**Comment by Gunasekkrann** [comment]
![Navigation steps not displayed](https://user-images.githubusercontent.com/93280986/144167429-b5f7c881-cb6d-447e-b852-2d4f46edb33b.PNG)

**Comment by Gunasekkrann** [comment]
![Popup messages handling issue](https://user-images.githubusercontent.com/93280986/144172390-469dbe18-66b0-44cd-8dd5-62ed56ac2faf.PNG)

**Comment by kcramakrishna** [comment]
I don't think we can differentiate between 'valid' clicks and 'invalid' clicks by user. Moving this to Holding Area fir future discussion.
