### ISSUE TITLE
Error message is not user friendly

### ISSUE THREAD

**Issue by Gunasekkrann** [Digital-Assistant/Digital_Assistant_Client#285]
When user nagivates to new tab, the error message displayed is not user friendly

![Error message not user friendly](https://user-images.githubusercontent.com/93280986/142024248-559001c3-b9e9-4132-9e7b-2026de2626e4.PNG)

**Comment by Gunasekkrann** [comment]
when clicked on UDAN Button our App still stays on the same page but in disabled form

**Comment by Gunasekkrann** [comment]
Once disabled...then am finding it difficult to enable it again

**Comment by kcramakrishna** [comment]
Changing the message to below:
This site's security policies may prevent UDAN from running well. Do you want to continue?

**Comment by kcramakrishna** [comment]
Introduce feature where clicking on disabled icon will prompt message: Do you want to enable "Universal Digital Assistant by Nistapp" with options "Enable" and "Keep suspended"
