### ISSUE TITLE
Sanity check of screen resolution to encourage usage on FHD - i.e. 1080p

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#288]
UDAN plugin creates UI issues on screens with resolution lesser than  1920x1080 (FHD)
We should check that screen resolution is equal to or more than FHD. 
If any param is lesser (i.e. height OR width) than FHD, we should pop-up a user choice screen 
"Current version of UDAN supports only FHD (1920x1080) resolution. Future versions will support more resolutions" "Exit UDAN"

**Comment by kcramakrishna** [comment]
Enable this with resolution_check=TRUE.
Test Engineers can set this variable to "FALSE" for testing.

**Comment by yureshwar** [comment]
Fixed issues that are appearing for 1080 resolution.
