### ISSUE TITLE
UDAN crashes quite frequently------When ever I tried executing the recorded steps...it crashes

### ISSUE THREAD

**Issue by Gunasekkrann** [Digital-Assistant/Digital_Assistant_Client#302]
![Udan crashed in Jira](https://user-images.githubusercontent.com/93280986/144283023-7d32eefb-8831-4b3c-8cf4-3074791497a5.PNG)

**Comment by yureshwar** [comment]
I am unable to reproduce the issue

![image](https://user-images.githubusercontent.com/516516/147194334-54f6a96d-5c6d-4250-b899-f50553d84397.png)


Need more details on this @Gunasekkrann when we can sit let me know

**Comment by Gunasekkrann** [comment]
Well its crashing again...you pickup any recorded steps and try executing it...what I see here is that the system is tring to find the point where we have started recording the steps....Example...

Steps
1.Click on Roadmap in Jira
2.When the Roadmap page is displayed, start recording the steps to reach to Burndown chart and complete the recording and save it.
3.Now navigate to any other page Jira and  starting playing the steps recorded earlier

Observed
System Crashed

Expected
system should smoothly take you to the Burndown page when played the recorded steps.

**Comment by yureshwar** [comment]
We have not implemented this kind of feature as of now. Thanks for suggesting. Will update once we have implemented this feature.

**Comment by Gunasekkrann** [comment]
I see this feature as little critical for our product to position in the market for the reason that say A customer currently in one particular page and he wanted to move to another...he will not go to home and then move to the desired one. Instead he would directly proceed from the links provided.
If Customer wants to use our App then he  is forced to move to Home then use our app.....which is not-good

**Comment by kcramakrishna** [comment]
This cannot be accomplished without major arch overhaul and integration ML/Ai. We will reject this for now.
