### ISSUE TITLE
Add boundary to tooltip to make it more visible.

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#304]
Also, check if there is improvement if we make the arrow/pointer triangle orange (or whatever color makes it look prominent)

"Create issue" modal is shifting to the right when tooltip appears. The position should not change. (Create separate task if this takes too long and you can't club it with above.)

**Comment by yureshwar** [comment]
Fixed the issue and is in testing phase

**Comment by yureshwar** [comment]
Added the boundary as specified.
