### ISSUE TITLE
Playback: Nothing happens after certain navigation during playback

### ISSUE THREAD

**Issue by yureshwar** [Digital-Assistant/Digital_Assistant_Client#306]
During the playback of recorded sequence it navigates for few recorded links and gets stopped at particular navigation and doesn't throw any error. In order to proceed further we need to click on pause and play button to complete the navigation.

Example recorded sequence: back to project

**Comment by Keerthireddy01** [comment]
issue been is been fixed.

**Comment by Keerthireddy01** [comment]
issue is been resolved and the recording is playing correctly.
