### ISSUE TITLE
Playback: Special dropdowns that got recorded are not playing properly

### ISSUE THREAD

**Issue by yureshwar** [Digital-Assistant/Digital_Assistant_Client#308]
Special dropdowns that are recorded during recording are not getting played back properly

Example: Report a bug

**Comment by Keerthireddy01** [comment]
while playing the recording it shows , error while playing the record.
![Screenshot (129)](https://user-images.githubusercontent.com/84083788/147208972-dd26f154-70be-49e8-8d7f-87f551802981.png)

**Comment by yureshwar** [comment]
Please re-record the sequence and check if it still persists

**Comment by yureshwar** [comment]
Re recorded and tested working as expected
