### ISSUE TITLE
Playback: Left menu not getting played during playback

### ISSUE THREAD

**Issue by yureshwar** [Digital-Assistant/Digital_Assistant_Client#311]
Left menu links which are recorded during recording sequence are not getting played. For example during recording if we click on PA Board which opens drop down menu and from it if we click on PA Board it gets recorded but during playback it doesn't play throws an error Nistapp ran into problem and will exit.

Example: Board testing

**Comment by Keerthireddy01** [comment]
while playing the recording it shows error while playing.
![Screenshot (130)](https://user-images.githubusercontent.com/84083788/147209211-5708ebdd-7962-4265-b305-38c446a6d7fd.png)
![Screenshot (131)](https://user-images.githubusercontent.com/84083788/147209218-a11835f5-01db-4209-aadd-6766067807bb.png)

**Comment by yureshwar** [comment]
Please re-record the sequence and check once again for the repition

**Comment by yureshwar** [comment]
Re recorded and tested working as expected.
