### ISSUE TITLE
Research if rapidJON can improve performance

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#363]
We do a lot of json comparison during playback. Any improvement in speed can massively improve UDA performance.  We should research https://rapidjson.org/index.html to see if it can help.
If it does, we should use this in our project. We can schedule this for version 1.2 or 1.3

But rapidjson is C++ library. There could be ways to use this in javascript/typescript. 
https://medium.com/jspoint/a-simple-guide-to-load-c-c-code-into-node-js-javascript-applications-3fcccf54fd32

This needs more research.

**Comment by yureshwar** [comment]
We have implemented Typescript-Json npm package https://www.npmjs.com/package/typescript-json
