### ISSUE TITLE
Issue with antd popover inside shadow dom

### ISSUE THREAD

**Issue by yureshwar** [Digital-Assistant/Digital_Assistant_Client#397]
We are rendering UDAN in shadow-dom. We are using popover js functionality of Antd in react. In shadow dom it is not rendering as expected.

**Comment by yureshwar** [comment]
![image](https://user-images.githubusercontent.com/516516/215022951-6b51f18b-a4b4-4b3f-ad83-c53937b43f94.png)

**Comment by kcramakrishna** [comment]
These links may give clues on the reasons of the bug and possible workarounds:
Code: https://codesandbox.io/s/shadowdom-antd-cx4ox?file=/src/App.js 

antd Bugs reports which detail the reasons:
https://github.com/ant-design/ant-design/issues/35897
https://github.com/ant-design/ant-design/issues/38911

**Comment by yureshwar** [comment]
Have to implement the configuration as given here

https://4x.ant.design/components/config-provider/

**Comment by yureshwar** [comment]
Fixed the bug in shadow dom
