### ISSUE TITLE
Parkoursc/Cloudleaf: Unable to record clicks due to circular reference.

### ISSUE THREAD

**Issue by yureshwar** [Digital-Assistant/Digital_Assistant_Client#420]
During recording unable to record click. 

When the user clicks on the clickable element we are trying to convert the DOM node to json and from json object to we are converting to string. During this conversion there are some circular references which are not getting end the loop. Due to this the browser is throwing the circular reference error. Please check as per the screenshot given

![image](https://user-images.githubusercontent.com/516516/235581288-7a31ac12-be96-43e5-9bfb-2317eb3e67d9.png)

**Comment by kcramakrishna** [comment]
https://www.npmjs.com/package/dom-to-json
https://github.com/sumn2u/dom-to-json
https://stackoverflow.com/questions/2303713/how-to-serialize-dom-node-to-json-even-if-there-are-circular-references
https://stackoverflow.com/questions/7993066/how-to-convert-html-dom-structure-to-json

**Comment by kcramakrishna** [comment]
The below plugins source code may have some clues:
https://chrome.google.com/webstore/detail/dom-to-json-converter/eipknbkoepfidigecmlofhmhlecmhfcj?hl=en
https://chrome.google.com/webstore/detail/dom-to-json-selector/mgnnbcacopddmbmikjmhadpchchcekln?hl=en

**Comment by kcramakrishna** [comment]
Possible solution:
Saving node: Clone the node -> Remove framework expandos/attributes) -> serialise_safe. Save this.
Comparing node: Clone the node -> Remove framework expandos/attributes), Fetch recorded node -> Deserialise it, Now compare both.

Can we instantiate multiple webworkers and exit once we find match ? This is not important now but could be potentially speed up our application.

Notes:
1. We can do comparison of nodes using webworkers ?
2. Just for information (may not be relevant in our case): We can pass serialised node to service worker: https://g.co/bard/share/1a715f0986df. 

**Detecting framework:**
detect-frontend: This library can detect a wide range of front-end frameworks, including Angular, React, Vue, Svelte, and Ember.

**Removing framework specific attributes**:
1. https://g.co/bard/share/e8a65f076dfb
4. https://g.co/bard/share/ad8bd3d10b07
5. https://g.co/bard/share/3e7af1aa45d8

**Serialisers**:
1. cycle.js: This library provides a generic serializer that can be used to serialize objects from any JavaScript framework.
2. json-stringify-safe: This library provides a safe version of the JSON.stringify() function that can be used to serialize objects without circular references.
3. serialize-javascript: This library provides a simple way to serialize JavaScript objects.
6. Framework specific serialisers also exist. i.e. https://g.co/bard/share/eb1416e80c65 

Cloning Nodes: https://g.co/bard/share/56c1a1d43e4d 
1. node.cloneNode - has optional param "deep"
2. importNode - has optional param to include children
