### ISSUE TITLE
Add screen resolution check in react application

### ISSUE THREAD

**Issue by yureshwar** [Digital-Assistant/Digital_Assistant_Client#443]
Enable UDA application for full hd resolution only as previously added functionality. #288

**Comment by kcramakrishna** [comment]
Do not enable for resolution lesser than HD-Ready: 1366*768
Give notification/alert for anything less than FDH: 1920*1080 - This is alert only. User cannot disable at all. No storage of any value in Browser storage. (Since there is no way to enable once you disable.)
