### ISSUE TITLE
Resolve 'deprecated' warnings when running 'npm install'

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#463]
1. How do we remove the below deprecated warnings  

$ npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated typescript-json@3.8.9: Renamed to typia

> Universal Digital Assistant (UDA) Beta@1.0.4.1 postinstall
> node ./scripts/postinstall.js

added 1288 packages, and audited 1289 packages in 3m

148 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by yureshwar** [comment]
Resolved this issue in commit 234f31e0
