### ISSUE TITLE
Resolve security vulnerabilities listed by 'npm install'

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#464]
$ npm install

> Universal Digital Assistant (UDA) Beta@1.0.4.1 postinstall
> node ./scripts/postinstall.js

added 1288 packages, and audited 1289 packages in 3m

148 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by yureshwar** [comment]
Resolved this issue in commit 234f31e0
