### ISSUE TITLE
Enable easy logging and debugging 

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#47]
Add a global variable 'logLevel' which can have values from 0-4(or5). 'logLevel=0' implies no logging at all and logging can increase with higher "logLevel" values. 
Survey and study different logging libraries for js. Identify the most useful, popular and high activity library to be adopted for our project.

**Comment by kcramakrishna** [comment]
This is related to #10

**Comment by kcramakrishna** [comment]
https://stackoverflow.com/questions/59618327/is-it-possible-to-pipe-all-browser-console-messages-errors-to-a-remote-machine
https://www.w3.org/TR/reporting/
https://developers.google.com/web/updates/2018/09/reportingapi#reportypes
https://rollbar.com/guides/javascript/where-are-javascript-errors-logged/#
https://github.com/winstonjs/winston

**Comment by yureshwar** [comment]
Do we need to zip the log messages

https://github.com/Stuk/jszip

**Comment by yureshwar** [comment]
ollect data as below

a. Log message contents
	1. OS info
	2. Browser info
	3. Html node element in which error occurs 
	4. User info
	5. Error message
	6. Client url
b. Also includes the below with server side programming
	1. Take IP address of clients along with User ID - (try to get ip address from apache or nodejs server)
