### ISSUE TITLE
Indexing script is sometimes leading to infinite loop conditions.

### ISSUE THREAD

**Issue by kcramakrishna** [Digital-Assistant/Digital_Assistant_Client#7]
This bug comes up intermittently. We have noticed this with external scripts like grammarly. We have noticed this without external scripts too - noticed that chrome-utility.audio service thread is maxing out. Need to identify the problem exactly.

**Comment by kcramakrishna** [comment]
Only 13 extensions have been able to cross the 10m mark - These 13 extensions include Google Translate, Adobe Acrobat, Tampermonkey, Avast Online Security, Adblock Plus, Adblock, uBlock Origin, Pinterest Save Button, Cisco Webex, Grammarly for Chrome, Skype, Avast SafePrice and Honey.

We will test for Google Translate, Avast (both) Adblock Plus, uBlock Origin, Grammarly for this version.

**Comment by yureshwar** [comment]
Tested with grammerly and adblock plus and the issue persists.
